name: CI

# Controla cuándo se ejecutará el workflow
on:
  # Se ejecuta en eventos de push o pull request solo en la rama "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Definición de uno o más jobs que pueden ejecutarse de forma secuencial o en paralelo
jobs:
  # Este workflow contiene un único job llamado "build"
  build:
    # El tipo de runner en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo
    steps:
      # Verifica el código fuente del repositorio para que el trabajo pueda acceder a él
      - uses: actions/checkout@v4

      # Ejecuta un comando simple
      - name: Run a one-line script
        run: echo Hello, world!

      # Ejecuta un conjunto de comandos
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Validación de archivos Markdown usando markdownlint
      - name: Check Markdown
        uses: actions/markdown-lint-action@v1
        with:
          files: '**/*.md'

      # Verificación de enlaces en los archivos Markdown
      - name: Check Links in Markdown
        run: |
          npm install -g markdown-link-check
          find . -name "*.md" | xargs -I {} markdown-link-check {}
